// Code generated by wire. DO NOT EDIT.
//go:build !wireinject

package app

import (
	"errors"
	"sync"

	"github.com/libtnb/chi-skeleton/internal/bootstrap"
	"github.com/libtnb/chi-skeleton/internal/conf"
	biz2 "github.com/libtnb/chi-skeleton/internal/order/biz"
	data2 "github.com/libtnb/chi-skeleton/internal/order/data"
	service2 "github.com/libtnb/chi-skeleton/internal/order/service"
	"github.com/libtnb/chi-skeleton/internal/pkg/registry"
	"github.com/libtnb/chi-skeleton/internal/server"
	"github.com/libtnb/chi-skeleton/internal/user/biz"
	"github.com/libtnb/chi-skeleton/internal/user/data"
	"github.com/libtnb/chi-skeleton/internal/user/service"
)

func InitializeApp(wireInput0 string) (*App, func() error, error) {
	var wireZero0 *App

	wireRunCleanup := func(cleanup func() error) (cleanupErr error, panicValue any) {
		defer func() { panicValue = recover() }()
		cleanupErr = cleanup()
		return cleanupErr, nil
	}

	var wireCleanups []func() error
	var wireCleanupOnce sync.Once
	var wireCleanupErr error
	var wireCleanupPanic any
	wireCleanup := func() error {
		wireCleanupOnce.Do(func() {
			var cleanupErrors []error
			for index := len(wireCleanups) - 1; index >= 0; index-- {
				cleanupErr, panicValue := wireRunCleanup(wireCleanups[index])
				if cleanupErr != nil {
					cleanupErrors = append(cleanupErrors, cleanupErr)
				}
				if panicValue != nil && wireCleanupPanic == nil {
					wireCleanupPanic = panicValue
				}
			}
			wireCleanupErr = errors.Join(cleanupErrors...)
		})
		if wireCleanupPanic != nil {
			panic(wireCleanupPanic)
		}
		return wireCleanupErr
	}

	wireCommitted := false
	defer func() {
		if !wireCommitted {
			panicValue := recover()
			func() {
				defer func() { _ = recover() }()
				_ = wireCleanup()
			}()
			if panicValue != nil {
				panic(panicValue)
			}
		}
	}()

	wireValue28_0, wireErr28 := conf.Load()
	if wireErr28 != nil {
		wireCommitted = true
		cleanupErr := wireCleanup()
		return wireZero0, nil, errors.Join(wireErr28, cleanupErr)
	}

	wireValue5_0, wireResourceCleanup5, wireErr5 := bootstrap.NewLogger(wireValue28_0)
	if wireErr5 != nil {
		wireCommitted = true
		cleanupErr := wireCleanup()
		return wireZero0, nil, errors.Join(wireErr5, cleanupErr)
	}
	if wireResourceCleanup5 != nil {
		wireCleanups = append(wireCleanups, wireResourceCleanup5)
	}

	wireValue6_0, wireResourceCleanup6, wireErr6 := bootstrap.NewData(wireValue28_0, wireValue5_0)
	if wireErr6 != nil {
		wireCommitted = true
		cleanupErr := wireCleanup()
		return wireZero0, nil, errors.Join(wireErr6, cleanupErr)
	}
	if wireResourceCleanup6 != nil {
		wireCleanups = append(wireCleanups, wireResourceCleanup6)
	}

	wireValue7_0 := bootstrap.ProvideDB(wireValue6_0)

	wireValue11_0, wireResourceCleanup11, wireErr11 := bootstrap.NewSession(wireValue28_0, wireValue5_0, wireValue7_0)
	if wireErr11 != nil {
		wireCommitted = true
		cleanupErr := wireCleanup()
		return wireZero0, nil, errors.Join(wireErr11, cleanupErr)
	}
	if wireResourceCleanup11 != nil {
		wireCleanups = append(wireCleanups, wireResourceCleanup11)
	}

	wireValue9_0, wireErr9 := bootstrap.NewValidator(wireValue28_0)
	if wireErr9 != nil {
		wireCommitted = true
		cleanupErr := wireCleanup()
		return wireZero0, nil, errors.Join(wireErr9, cleanupErr)
	}

	wireValue37_0 := bootstrap.DatabaseHealthCheck(wireValue6_0)

	wireValue41_0 := make(registry.HealthChecks, 0, 1)
	wireValue41_0 = append(wireValue41_0, wireValue37_0)

	wireValue40_0 := server.HealthRoutes(wireValue41_0)

	wireValue42_0 := server.WsRoutes()

	wireValue17_0 := data.NewUserRepo(wireValue7_0)

	wireValue18_0 := biz.NewUserUsecase(wireValue17_0)

	wireValue19_0 := service.NewUserService(wireValue18_0, wireValue9_0)

	wireValue43_0 := service.UserRoutes(wireValue19_0)

	wireValue22_0 := data2.NewOrderRepo(wireValue7_0)

	wireValue23_0 := data2.NewUsers(wireValue18_0)

	wireValue10_0 := bootstrap.NewBus(wireValue5_0)

	wireValue24_0 := biz2.NewOrderUsecase(wireValue22_0, wireValue23_0, wireValue10_0)

	wireValue25_0 := service2.NewOrderService(wireValue24_0, wireValue9_0)

	wireValue45_0 := service2.OrderRoutes(wireValue25_0)

	wireValue47_0 := make(registry.Routes, 0, 4)
	wireValue47_0 = append(wireValue47_0, wireValue40_0)
	wireValue47_0 = append(wireValue47_0, wireValue42_0)
	wireValue47_0 = append(wireValue47_0, wireValue43_0)
	wireValue47_0 = append(wireValue47_0, wireValue45_0)

	wireValue29_0 := server.NewVersion(wireInput0)

	wireValue31_0, wireErr31 := server.NewRouter(wireValue28_0, wireValue5_0, wireValue11_0, wireValue9_0, wireValue47_0, wireValue29_0)
	if wireErr31 != nil {
		wireCommitted = true
		cleanupErr := wireCleanup()
		return wireZero0, nil, errors.Join(wireErr31, cleanupErr)
	}

	wireValue32_0 := server.NewHTTP(wireValue28_0, wireValue31_0)

	wireValue12_0, wireErr12 := bootstrap.NewMigrate(wireValue7_0, wireValue5_0)
	if wireErr12 != nil {
		wireCommitted = true
		cleanupErr := wireCleanup()
		return wireZero0, nil, errors.Join(wireErr12, cleanupErr)
	}

	wireValue38_0 := bootstrap.Heartbeat(wireValue5_0)

	wireValue48_0 := make(registry.Jobs, 0, 1)
	wireValue48_0 = append(wireValue48_0, wireValue38_0)

	wireValue30_0, wireErr30 := bootstrap.NewCron(wireValue5_0, wireValue48_0)
	if wireErr30 != nil {
		wireCommitted = true
		cleanupErr := wireCleanup()
		return wireZero0, nil, errors.Join(wireErr30, cleanupErr)
	}

	wireValue46_0 := service2.NewOrderPlacedLogger(wireValue10_0, wireValue5_0)

	wireValue49_0 := make(registry.Subscriptions, 0, 1)
	wireValue49_0 = append(wireValue49_0, wireValue46_0)

	wireValue34_0 := NewApp(wireValue28_0, wireValue32_0, wireValue12_0, wireValue30_0, wireValue49_0)

	wireCommitted = true

	return wireValue34_0, wireCleanup, nil
}

func InitializeCLI() (*Cli, func() error, error) {
	var wireZero0 *Cli

	wireRunCleanup := func(cleanup func() error) (cleanupErr error, panicValue any) {
		defer func() { panicValue = recover() }()
		cleanupErr = cleanup()
		return cleanupErr, nil
	}

	var wireCleanups []func() error
	var wireCleanupOnce sync.Once
	var wireCleanupErr error
	var wireCleanupPanic any
	wireCleanup := func() error {
		wireCleanupOnce.Do(func() {
			var cleanupErrors []error
			for index := len(wireCleanups) - 1; index >= 0; index-- {
				cleanupErr, panicValue := wireRunCleanup(wireCleanups[index])
				if cleanupErr != nil {
					cleanupErrors = append(cleanupErrors, cleanupErr)
				}
				if panicValue != nil && wireCleanupPanic == nil {
					wireCleanupPanic = panicValue
				}
			}
			wireCleanupErr = errors.Join(cleanupErrors...)
		})
		if wireCleanupPanic != nil {
			panic(wireCleanupPanic)
		}
		return wireCleanupErr
	}

	wireCommitted := false
	defer func() {
		if !wireCommitted {
			panicValue := recover()
			func() {
				defer func() { _ = recover() }()
				_ = wireCleanup()
			}()
			if panicValue != nil {
				panic(panicValue)
			}
		}
	}()

	wireValue28_0, wireErr28 := conf.Load()
	if wireErr28 != nil {
		wireCommitted = true
		cleanupErr := wireCleanup()
		return wireZero0, nil, errors.Join(wireErr28, cleanupErr)
	}

	wireValue5_0, wireResourceCleanup5, wireErr5 := bootstrap.NewLogger(wireValue28_0)
	if wireErr5 != nil {
		wireCommitted = true
		cleanupErr := wireCleanup()
		return wireZero0, nil, errors.Join(wireErr5, cleanupErr)
	}
	if wireResourceCleanup5 != nil {
		wireCleanups = append(wireCleanups, wireResourceCleanup5)
	}

	wireValue6_0, wireResourceCleanup6, wireErr6 := bootstrap.NewData(wireValue28_0, wireValue5_0)
	if wireErr6 != nil {
		wireCommitted = true
		cleanupErr := wireCleanup()
		return wireZero0, nil, errors.Join(wireErr6, cleanupErr)
	}
	if wireResourceCleanup6 != nil {
		wireCleanups = append(wireCleanups, wireResourceCleanup6)
	}

	wireValue7_0 := bootstrap.ProvideDB(wireValue6_0)

	wireValue12_0, wireErr12 := bootstrap.NewMigrate(wireValue7_0, wireValue5_0)
	if wireErr12 != nil {
		wireCommitted = true
		cleanupErr := wireCleanup()
		return wireZero0, nil, errors.Join(wireErr12, cleanupErr)
	}

	wireValue38_0 := bootstrap.MigrateCommand(wireValue12_0)

	wireValue17_0 := data.NewUserRepo(wireValue7_0)

	wireValue18_0 := biz.NewUserUsecase(wireValue17_0)

	wireValue43_0 := service.UserCommand(wireValue18_0)

	wireValue46_0 := make(registry.Commands, 0, 2)
	wireValue46_0 = append(wireValue46_0, wireValue38_0)
	wireValue46_0 = append(wireValue46_0, wireValue43_0)

	wireValue33_0 := newRootCommand(wireValue46_0)

	wireValue35_0 := NewCli(wireValue33_0)

	wireCommitted = true

	return wireValue35_0, wireCleanup, nil
}
